apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: hello-tap
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  source:
    git:
      url: https://github.com/trisberg/hello-tap
      ref:
        branch: main
